meeting/urls.py
from django.urls import path
from .views import CreateMeetingView, UpdateMeetingView, UserMeetingListView, RoomView, CreateOrGetMeetingMember

app_name = 'meeting'


urlpatterns = [
    path('create/', CreateMeetingView.as_view(), name='create'),
    path('update/<int:id>', UpdateMeetingView.as_view(), name='update'),
    path('list/', UserMeetingListView.as_view(), name='list'),

    path('room/<str:channel_name>', RoomView.as_view(), name='room'),

    path('member/get/<int:uid>/<str:channel_name>/', CreateOrGetMeetingMember.as_view(), name='member_get'),
    path('member/create/', CreateOrGetMeetingMember.as_view(), name='member_create'),
]

quran/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from .views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catalog'),

    path('meeting/', include('meeting.urls', namespace='meeting')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', homepage, name='home')
]

meeting/models.py
import os
import binascii
from datetime import timedelta

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.utils.html import format_html
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError
from django.contrib.auth.backends import get_user_model
from django.forms.models import model_to_dict

from .utils import generate_agora_token


User = get_user_model()


STATUS = (
    ('coming', 'Coming'),
    ('progress', 'Progress'),
    ('finished', 'Finished'),
    ('cancelled', 'Canceled'),
)


class Meeting(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, default='coming', max_length=20)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    channel_name = models.CharField(null=True, blank=True, unique=True, max_length=100)

    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    start_at = models.DateTimeField()
    end_at = models.DateTimeField()

    token = models.CharField(max_length=150, null=True, blank=True)
    uid = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_meeting_url(self, request):
        protocol = request.scheme + "://"
        domain = request.META['HTTP_HOST']
        view_oath = reverse('meeting:room', args=[self.channel_name, ])
        return protocol + domain + view_oath

    def get_meeting_link(self, request):
        if self.is_timely_available():
            link = self.get_meeting_url(request)
            return format_html('<a href="{}">{}</a>', link, 'GO Room')
        return "--"

    @staticmethod
    def generate_key():
        return binascii.hexlify(os.urandom(20)).decode()

    def is_timely_available(self):
        current = timezone.now()
        start_time = self.start_at - timedelta(minutes=15)
        end_time = self.end_at + timedelta(seconds=settings.AGORA_INCREASE_TIME)
        return start_time <= current <= end_time


class MeetingMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    meeting = models.ForeignKey(Meeting, on_delete=models.SET_NULL, null=True)
    token = models.CharField(max_length=150, null=True, blank=True)
    uid = models.IntegerField(null=True, blank=True)

    class Meta:
        unique_together = ('user', 'meeting')

    def as_dict(self):
        return {
            "user": model_to_dict(self.user, fields=('id', 'username', 'first_name', 'last_name', 'email')),
            "meeting": model_to_dict(self.meeting, exclude=('token', 'uid')),
            "token": self.token,
            "uid": self.uid
        }


@receiver(post_save, sender=Meeting)
def create_meeting_channel(sender, instance, created, **kwargs) -> None:
    if not created:
        return

    channel_name = sender.generate_key()
    instance.channel_name = channel_name
    try:
        token, uid = generate_agora_token(channel_name=channel_name, expiration_time=instance.end_at.timestamp())
        instance.token = token
        instance.uid = uid
    except Exception as e:
        print(e)
    finally:
        instance.save()


@receiver(post_save, sender=MeetingMember)
def create_member_credentials(sender, instance, created, **kwargs) -> None:
    if not created:
        return

    channel_name = instance.meeting.channel_name
    end_time = instance.meeting.end_at.timestamp()
    try:
        token, uid = generate_agora_token(channel_name=channel_name, expiration_time=end_time)
        instance.token = token
        instance.uid = uid
    except Exception as e:
        print(e)
    finally:
        instance.save()

meeting/forms.py
from django import forms
from django.contrib.admin import widgets

from .models import Meeting, MeetingMember


class CreateMeetingForm(forms.ModelForm):
    start_at = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime(), required=True)
    end_at = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime(), required=True)

    class Meta:
        model = Meeting
        fields = [
           'status', 'title', 'description', 'start_at', 'end_at'
        ]


class UpdateMeetingForm(forms.ModelForm):
    start_at = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime(), required=True)
    end_at = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime(), required=True)

    class Meta:
        model = Meeting
        fields = [
           'status', 'title', 'description', 'start_at', 'end_at'
        ]


class WaitingForm(forms.Form):
    name = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))


class CreateMeetingMember(forms.Form):
    user = forms.IntegerField(required=True)
    meeting = forms.IntegerField(required=True)

meeting/views.py
from django.conf import settings
from django.http.response import JsonResponse
from django.urls import reverse, reverse_lazy
from django.urls.exceptions import NoReverseMatch
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, CreateView, UpdateView, ListView, DetailView, FormView
from django.contrib.auth.backends import get_user_model
from .utils import generate_agora_token
from .models import Meeting, MeetingMember
from .forms import CreateMeetingForm, UpdateMeetingForm, WaitingForm, CreateMeetingMember


User = get_user_model()


class CreateMeetingView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Meeting
    form_class = CreateMeetingForm
    template_name = 'meeting/create.html'
    extra_context = {
        'title': 'Create Meeting'
    }
    success_url = reverse_lazy('meeting:list')
    success_message = "Meeting has created successfully"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class UpdateMeetingView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Meeting
    form_class = UpdateMeetingForm
    pk_url_kwarg = "id"
    template_name = 'meeting/update.html'
    extra_context = {
        'title': 'Update Meeting'
    }
    success_url = reverse_lazy('meeting:list')
    success_message = "Meeting has updated successfully"


class UserMeetingListView(LoginRequiredMixin, ListView):
    model = Meeting
    template_name = 'meeting/list.html'
    extra_context = {
        'title': 'Meeting List'
    }
    context_object_name = "meetings"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user).order_by('-created')


class RoomView(LoginRequiredMixin, DetailView):
    model = Meeting
    context_object_name = 'room'
    slug_url_kwarg = 'channel_name'
    template_name = 'meeting/room.html'

    redirect_url = 'meeting:waiting'
    redirect_message = "The time hasn't come yet or it has already pass"

    extra_context = {
        'title': 'Meeting Room',
        'app_id': settings.AGORA_APP_ID,
    }

    def get_redirect_message(self):
        return self.redirect_message

    def get_redirect_url(self):
        return self.redirect_url

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj.is_timely_available():
            messages.error(self.request, self.get_redirect_message())
            return redirect(self.get_redirect_url())
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        obj = get_object_or_404(self.model, **{self.slug_url_kwarg: slug})
        return obj


@method_decorator(csrf_exempt, name='dispatch')
class CreateOrGetMeetingMember(View):
    pk_field = "uid"
    pk_url_kwarg = "uid"
    slug_field = "meeting__channel_name"
    slug_url_kwarg = "channel_name"
    model = MeetingMember
    response_class = JsonResponse
    form_class = CreateMeetingMember
    http_method_names = ("get", "post")

    def render_to_response(self, context, **response_kwargs):
        """Render the response class."""
        return self.response_class(data=context, **response_kwargs)

    def get_object(self):
        """Get object or raise 404 error."""
        obj = get_object_or_404(
            self.model,
            **{
                self.pk_field: self.kwargs.get(self.pk_url_kwarg),
                self.slug_field: self.kwargs.get(self.slug_url_kwarg)
            }
        )
        return obj.as_dict()

    def get(self, request, uid=None, channel_name=None, *args, **kwargs):
        """Get object model"""
        if uid is None or channel_name is None:
            raise NoReverseMatch(f"URL missing one attribute ({self.url_kwarg})")
        context = {'data': self.get_object()}
        return self.render_to_response(context, **kwargs)

    def get_form_class(self):
        """Return the form class to use."""
        return self.form_class

    def post(self, request, *args, **kwargs):
        """Create object model."""
        Form = self.get_form_class()
        form = Form(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            data["meeting"] = get_object_or_404(Meeting, id=data.pop("meeting"))
            data["user"] = get_object_or_404(User, id=data.pop("user"))
            instance, created = self.model.objects.get_or_create(**data)
            context = {"data":  instance.as_dict()}
            kwargs.update({"status": 201 if created else 200})
            return self.render_to_response(context, **kwargs)

        context = {"errors": {f: e.get_json_data() for f, e in form.errors.items()}}
        kwargs.update({"status": 400})
        return self.render_to_response(context, **kwargs)

templates/meeting/create.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
{% include 'base/admin_style.html' %}
<form method="POST" class="contact-form" style="width:65%; align:center; margin: 0 auto; margin-top:35px;">
   <h4 style="text-align:center;">{{ title }}</h4>
   {{ form.media }}
   {% csrf_token %}
   {{ form.as_p }}
   <div class="d-grid" style="margin-top:10px;">
       <button class="btn btn-dark btn-lg " id="submitButton" type="submit">Submit</button>
   </div>
</form>
{% endblock %}

templates/meeting/list.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
<h4>Meeting List View:</h4> <span style="display: inline-block;"> <a href="{% url 'meeting:create' %}">Create</a> </span>
{% if meetings %}
<table class="table table-striped" style="margin: 20px">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Created</th>
        <th scope="col">Modified</th>
        <th scope="col">Start At</th>
        <th scope="col">End At</th>
        <th scope="col">Edit</th>
        <th scope="col">Link</th>
    </tr>
    </thead>
    <tbody>
        {% for meeting in meetings %}
        <tr>
            <th scope="row">{{ forloop.index }}</th>
            <td>{{ meeting.title }}</td>
            <td>{{ meeting.description }}</td>
            <td>{{ meeting.created|timesince }}</td>
            <td>{{ meeting.modified|timesince }}</td>
            <td>{{ meeting.start_at|timesince }}</td>
            <td>{{ meeting.end_at|timesince }}</td>
            <td><a href="{% url 'meeting:update' meeting.pk %}">Update</a></td>
            <td>{% if meeting.is_timely_available %}<a href="{% url 'meeting:room' meeting.channel_name %}">Link</a>{% else %}--{% endif %}</td>
        </tr>
        {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            <span class="page-link">Previous</span>
        </li>
        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
            <li class="page-item active" aria-current="page"><span class="page-link">{{ page }}</span></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{page}}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            <a class="page-link" href="#">Next</a>
        </li>
  </ul>
</nav>
{% endif %}

{% else %}
<span style="color:red;">No Meetings To View</span>
{% endif %}
{% endblock %}

templates/meeting/room.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>MyChat</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='{% static "css/main.css" %}'>
    <!-- <script src='main.js'></script> -->
</head>
<body>

    <main>
        <section id="room-name-wrapper">
            <p>Room Name: <span>{{ room.title }}</span></p>
        </section>

                <div id="video-streams">

<!--                    <div class="video-container" id="user-container-1">-->
<!--                        <div class="video-player" id="user-1"></div>-->
<!--                        <div class="username-wrapper"><span class="user-name">Dennis Ivanov</span></div>-->
<!--                    </div>-->

<!--                    <div class="video-container" id="user-container-2">-->
<!--                        <div class="video-player" id="user-2"></div>-->
<!--                        <div class="username-wrapper"><span class="user-name">Sam</span></div>-->
<!--                    </div>-->

<!--                    <div class="video-container" id="user-container-3">-->
<!--                        <div class="video-player" id="user-3"></div>-->
<!--                        <div class="username-wrapper"><span class="user-name">Peter</span></div>-->
<!--                    </div>-->

<!--                    <div class="video-container" id="user-container-4">-->
<!--                        <div class="video-player" id="user-4"></div>-->
<!--                        <div class="username-wrapper"><span class="user-name">Erik</span></div>-->
<!--                    </div>-->

<!--                    <div class="video-container" id="user-container-4">-->
<!--                        <div class="video-player" id="user-5"></div>-->
<!--                        <div class="username-wrapper"><span class="user-name">Paul</span></div>-->
<!--                    </div>-->
                </div>

        <section id="controls-wrapper">
            <div class="icon-wrapper">
                <img class="control-icon" id="mic-btn" src="{% static 'images/microphone.svg' %}" title="Mute Mic"/>
            </div>

            <div class="icon-wrapper">
                <img class="control-icon" id="camera-btn" src="{% static 'images/video.svg' %}" title="Close Camera"/>
            </div>

            <div class="icon-wrapper">
                <img class="control-icon" id="leave-btn" src="{%static 'images/leave.svg' %}" title="Leave Meeting"/>
            </div>
        </section>
    </main>
    {{ app_id|json_script:"app_id" }}
    {{ room.token|json_script:"token" }}
    {{ room.uid|json_script:"uid" }}
    {{ room.channel_name|json_script:"channel" }}
    {{ room.id|json_script:"room_id" }}
    {{ request.user.id|json_script:"user_id" }}
    <script type="text/javascript" src="{% static 'assets\AgoraRTC_N-4.11.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/streams.js' %}"></script>
</body>
</html>

templates/meeting/update.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
{% include 'base/admin_style.html' %}

<form method="POST" class="contact-form" style="width:65%; align:center; margin: 0 auto; margin-top:35px;">
   <h4 style="text-align:center;">{{ title }}</h4>
   {% csrf_token %}
   {{ form.as_p }}
   <div class="d-grid" style="margin-top:10px;">
       <button class="btn btn-dark btn-lg " id="submitButton" type="submit">Submit</button>
   </div>
</form>
{% endblock %}

templates/meeting/waiting.html
{% extends 'base.html' %}

{% load static %}


{% block extra_style %}
<link rel='stylesheet' type='text/css' media='screen' href='{% static "css/main.css" %}'>
{% endblock %}

{% block content %}
<section id="form-container" style="position: block;">
    <img id="logo" src="{% static 'images/chat-icon.png' %}"/>

    <div id="welcome-message">
        <h1>Welcome to Quran</h1>
        <p>Join the room!</p>
    </div>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-field">
            <input type="submit"  value="Join Room">
        </div>
    </form>

</section>
{% endblock %}